version: "3.9"
services:
  base: &base
    image: thulirpygeo
    working_dir: /code
    volumes:
      - .:/code
  env:
    <<: *base
    command: env
  ls:
    <<: *base
    command: ls
  shell:
    <<: *base
    command: sh
  python:
    <<: *base
    command: python
  run:
    <<: *base
    command: python /code/main.py
  build:
    <<: *base
    command: ls
  jupyterlab:
    <<: *base

volumes:
  logvolume01: {}