version: "3.9"
services:
  base: &base
    image: geo-parser_build
    working_dir: /code
    volumes:
      - .:/code
      - /Users/rajanp/research/images/Bulk Order known-good-tn/Landsat 8 OLI_TIRS C1 Level-1/LC08_L1TP_143054_20200730_20200807_01_T1:/tmp
  env:
    <<: *base
    command: env
  ls:
    <<: *base
    command: ls
  shell:
    <<: *base
    command: sh
  python:
    <<: *base
    command: python
  run:
    <<: *base
    command: python /code/main.py
  build:
    <<: *base
    command: ls

volumes:
  logvolume01: {}